@ECHO OFF

IF "%1" == "Prod" GOTO PRODMODE
SET TMPFLAGS=/D_DEBUG /Zi /MDd
GOTO BUILD

:PRODMODE
SET TMPFLAGS=/Og /Oi /Ob1 /Op /DNDEBUG /MD
GOTO BUILD


:BUILD
cl /W3 /DWIN32 %TMPFLAGS% /EHa /GR /D_WIN32_WINNT=0x0500 TmpTest.cpp user32.lib kernel32.lib WSock32.lib


REM /DUNICODE /D_UNICODE  gdi32.lib

