// ----------------------------------------------------------------------------
//  FILE: CIDMetaExtr_Shared.cpp
//  DATE: Sat, Dec 07 22:19:59 2019 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDMetaExtr_.hpp"

