// ----------------------------------------------------------------------------
//  FILE: CIDMetaExtr_Shared.cpp
//  DATE: Tue, Sep 24 17:51:15 2019 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDMetaExtr_.hpp"

