// ----------------------------------------------------------------------------
//  FILE: CIDMetaExtr_Shared.cpp
//  DATE: Mon, Dec 02 17:25:35 2019 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDMetaExtr_.hpp"

