// ----------------------------------------------------------------------------
//  FILE: CIDMetaExtr_Shared.hpp
//  DATE: Wed, Jun 26 17:43:28 2019 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDMetaExtr
{
}

#pragma CIDLIB_POPPACK

