// ----------------------------------------------------------------------------
//  FILE: TestOrb3_IntfClientProxy.hpp
//  DATE: Tue, Feb 26 15:38:53 2019 -0500
//    ID: 9E7B4A7A069E4160-578F52288498BBF0
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TTestOrb3IntfClientProxy : public TOrbClientBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;

        // --------------------------------------------------------------------
        // Public Constructors and Destructor
        // --------------------------------------------------------------------
        TTestOrb3IntfClientProxy();
        TTestOrb3IntfClientProxy(const TOrbObjId& ooidSrc, const TString& strNSBinding);
        TTestOrb3IntfClientProxy(const TTestOrb3IntfClientProxy&) = delete;
        ~TTestOrb3IntfClientProxy();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TTestOrb3IntfClientProxy& operator=(const TTestOrb3IntfClientProxy&) = delete;

        // --------------------------------------------------------------------
        // Public, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid SetObjId
        (
            const   TOrbObjId& ooidToSet
            , const TString& strNSBinding
            , const tCIDLib::TBoolean bCheck = kCIDLib::True
        )   override;

        // --------------------------------------------------------------------
        // Public, non-virtual methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid AddToBuf
        (
            tCIDLib::TCard4& c4BufSz_mbufToAdjust
            , THeapBuf& mbufToAdjust
        );

        tCIDLib::TCard4 c4AddTo
        (
            const tCIDLib::TCard4 c4ToAdjust
        );

        tCIDLib::TVoid DelayRet();

        tCIDLib::TVoid NoParmsNoRet();

        TString strFormatValue
        (
            const tCIDLib::TCard4 c4ToFormat
        );

        tCIDLib::TVoid UploadBuf
        (
            const tCIDLib::TCard4 c4BufSz_mbufUpload
            , const TMemBuf& mbufUpload
        );

    protected :
        // --------------------------------------------------------------------
        // Declare our friends
        // --------------------------------------------------------------------
        friend class TFacCIDOrb;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TTestOrb3IntfClientProxy,TOrbClientBase)
};

#pragma CIDLIB_POPPACK

inline tCIDLib::TVoid
TTestOrb3IntfClientProxy::SetObjId(const  TOrbObjId& ooidToSet
              , const TString& strNSBinding
              , const tCIDLib::TBoolean bCheck)
{
    TParent::SetObjId(ooidToSet, strNSBinding, bCheck);
}

