// ----------------------------------------------------------------------------
//  FILE: CIDDAE_Shared.hpp
//  DATE: Sat, May 01 11:54:20 2021 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDDAE
{
}

#pragma CIDLIB_POPPACK

