// ----------------------------------------------------------------------------
//  FILE: CIDDAE_Shared.cpp
//  DATE: Tue, Jan 19 17:36:47 2021 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDDAE_.hpp"

