// ----------------------------------------------------------------------------
//  FILE: CIDDAE_Shared.cpp
//  DATE: Tue, Feb 26 15:38:53 2019 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDDAE_.hpp"

