// ----------------------------------------------------------------------------
//  FILE: VideoDemoS_IntfServerBase.hpp
//  DATE: Wed, Jan 30 13:17:30 2019 -0500
//    ID: E1CCC9CBCFA1FDAF-29A8F7CB04763265
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TVideoDemoServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;


        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TVideoDemoServerBase(const TVideoDemoServerBase&) = delete;
        ~TVideoDemoServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TVideoDemoServerBase& operator=(const TVideoDemoServerBase&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TBoolean bQueryByName
        (
            const TString& strToFind
            , TDemoRecord& recFound
        ) = 0;

        virtual tCIDLib::TBoolean bQueryAllStatus
        (
            const tVideoDemoSh::EStatus eToFind
            , TVector<TDemoRecord>& colFound
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TVideoDemoServerBase();
        TVideoDemoServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TVideoDemoServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

