// ----------------------------------------------------------------------------
//  FILE: CIDOrbUC_CoreAdminServerBase.hpp
//  DATE: Tue, Sep 24 17:51:15 2019 -0400
//    ID: 2117FF72EE8BD81D-F320AE6BEB1B2F0C
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class CIDORBUCEXP TCIDCoreAdminServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TCIDCoreAdminServerBase(const TCIDCoreAdminServerBase&) = delete;
        ~TCIDCoreAdminServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TCIDCoreAdminServerBase& operator=(const TCIDCoreAdminServerBase&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TVoid AdminStop() = 0;

        virtual tCIDLib::TBoolean bPollValuesInScope
        (
            const TString& strParScope
            , const tCIDLib::TBoolean bDirectOnly
            , const tCIDLib::TCard8 c8QueryStamp
            , tCIDLib::TCard8& c8PollStamp
            , TFundVector<tCIDLib::TCard4>& fcolIds
            , TFundVector<tCIDLib::TCard8>& fcolValues
        ) = 0;

        virtual tCIDLib::TCard4 c4QueryStats
        (
            const TString& strParScope
            , TVector<TStatsCacheItemInfo>& colItems
            , const tCIDLib::TBoolean bDirectOnly
            , tCIDLib::TCard8& c8Stamp
        ) = 0;

        virtual tCIDLib::TVoid QueryBasicInfo
        (
            TString& strHostName
            , TString& strProcName
            , tCIDLib::TCard4& c4CPUCount
            , TString& strOSInfo
            , tCIDLib::TCard8& c8StartTime
        ) = 0;

        virtual tCIDLib::TVoid SetModLogLevel
        (
            const TString& strModule
            , const TString& strLevel
        ) = 0;

        virtual tCIDLib::TVoid SetModLogTrace
        (
            const TString& strModule
            , const tCIDLib::TBoolean bState
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TCIDCoreAdminServerBase();
        TCIDCoreAdminServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TCIDCoreAdminServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

