// ----------------------------------------------------------------------------
//  FILE: CIDAudStream_Shared.hpp
//  DATE: Sat, Oct 05 19:48:04 2019 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDAudStream
{
    
    // ------------------------------------------------------------------------
    //  The possible statuses of a derivative of our base source stream.
    //                  
    // ------------------------------------------------------------------------
    enum class EStrmStates
    {
        Ready
        , Error
        , WaitConnect
        , Count
        , Min = Ready
        , Max = WaitConnect
    };
    CIDAUDSTREAMEXP EStrmStates eXlatEStrmStates(const TString& strToXlat, const tCIDLib::TBoolean bThrowIfNot = kCIDLib::False);
    CIDAUDSTREAMEXP const TString& strXlatEStrmStates(const EStrmStates eToXlat, const tCIDLib::TBoolean bThrowIfNot = kCIDLib::True);
    CIDAUDSTREAMEXP tCIDLib::TBoolean bIsValidEnum(const EStrmStates eVal);

}

#pragma CIDLIB_POPPACK

CIDAUDSTREAMEXP TTextOutStream& operator<<(TTextOutStream& strmTar, const tCIDAudStream::EStrmStates eToStream);

