// ----------------------------------------------------------------------------
//  FILE: CIDAudStream_Shared.hpp
//  DATE: Fri, Feb 12 21:10:39 2021 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDAudStream
{
    
    // ------------------------------------------------------------------------
    //  The possible statuses of a derivative of our base source stream.
    //                  
    // ------------------------------------------------------------------------
    enum class EStrmStates
    {
        Ready
        , Error
        , WaitConnect
        , Count
        , Min = Ready
        , Max = WaitConnect
    };
    [[nodiscard]] CIDAUDSTREAMEXP EStrmStates eXlatEStrmStates(const TString& strToXlat, const tCIDLib::TBoolean bThrowIfNot = kCIDLib::False);
    [[nodiscard]] CIDAUDSTREAMEXP const TString& strXlatEStrmStates(const EStrmStates eToXlat, const tCIDLib::TBoolean bThrowIfNot = kCIDLib::True);
    [[nodiscard]] CIDAUDSTREAMEXP tCIDLib::TBoolean bIsValidEnum(const EStrmStates eVal);

    CIDAUDSTREAMEXP TTextOutStream& operator<<(TTextOutStream& strmTar, const tCIDAudStream::EStrmStates eToStream);
}

#pragma CIDLIB_POPPACK


