// ----------------------------------------------------------------------------
//  FILE: TestCIDLib2_IDLGen.hpp
//  DATE: Tue, Jan 19 17:36:48 2021 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tTestCIDLib2
{
    
    // ------------------------------------------------------------------------
    //  For testing contiguous enums
    //                  
    // ------------------------------------------------------------------------
    enum class ETest1
    {
        Value1
        , Value2
        , Value3
        , Value4
        , Value5
        , Count
        , Min = Value1
        , Max = Value5
        , StartVal = Value2
        , EndVal = Value4
    };
    [[nodiscard]]  tCIDLib::TBoolean bIsValidEnum(const ETest1 eVal);

    inline tTestCIDLib2::ETest1 operator++(tTestCIDLib2::ETest1& eVal, int)
    {
        tTestCIDLib2::ETest1 eTmp = eVal;
        eVal = tTestCIDLib2::ETest1(int(eVal)+1);
        return eTmp;
    }

     TTextOutStream& operator<<(TTextOutStream& strmTar, const tTestCIDLib2::ETest1 eToStream);
}

#pragma CIDLIB_POPPACK


