// ----------------------------------------------------------------------------
//  FILE: CIDSpReco_Shared.cpp
//  DATE: Sat, May 01 11:54:19 2021 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDSpReco_.hpp"

const TString kCIDSpReco::strVal_MapPref(L"Map_");
const TString kCIDSpReco::strRule_TopRule(L"TopRule");
const TString kCIDSpReco::strPath_Root(L"/");
