// ----------------------------------------------------------------------------
//  FILE: CIDSpReco_Shared.cpp
//  DATE: Tue, Feb 26 15:38:52 2019 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDSpReco_.hpp"

const TString kCIDSpReco::strVal_MapPref(L"Map_");
const TString kCIDSpReco::strRule_TopRule(L"TopRule");
const TString kCIDSpReco::strPath_Root(L"/");
