// ----------------------------------------------------------------------------
//  FILE: TestOrb2_ServerBase.hpp
//  DATE: Tue, Feb 26 15:38:53 2019 -0500
//    ID: 04B5C1BC4E24325C-2549453D6539A000
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TTestOrb2IntfServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TTestOrb2IntfServerBase(const TTestOrb2IntfServerBase&) = delete;
        ~TTestOrb2IntfServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TTestOrb2IntfServerBase& operator=(const TTestOrb2IntfServerBase&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TVoid Ping() = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TTestOrb2IntfServerBase();
        TTestOrb2IntfServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TTestOrb2IntfServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

