// ----------------------------------------------------------------------------
//  FILE: TestOrb2_ServerBase.cpp
//  DATE: Tue, Mar 12 00:36:51 2019 -0400
//    ID: 04B5C1BC4E24325C-2549453D6539A000
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Includes
// ----------------------------------------------------------------------------
#include "TestOrb2.hpp"

// ----------------------------------------------------------------------------
// Magic macros
// ----------------------------------------------------------------------------
RTTIDecls(TTestOrb2IntfServerBase,TOrbServerBase)


// ----------------------------------------------------------------------------
// Public, static data
// ----------------------------------------------------------------------------
const TString TTestOrb2IntfServerBase::strInterfaceId(L"04B5C1BC4E24325C-2549453D6539A000");
// ----------------------------------------------------------------------------
// TTestOrb2IntfServerBase: Destructor
// ----------------------------------------------------------------------------
TTestOrb2IntfServerBase::~TTestOrb2IntfServerBase()
{
}

// ----------------------------------------------------------------------------
// TTestOrb2IntfServerBase: Protected Constructors
// ----------------------------------------------------------------------------
TTestOrb2IntfServerBase::TTestOrb2IntfServerBase() :
    TOrbServerBase(strInterfaceId, L"TTestOrb2IntfClientProxy" )
{
}

TTestOrb2IntfServerBase::TTestOrb2IntfServerBase(const TOrbObjId& ooidThis) :
    TOrbServerBase(ooidThis)
{
}

// ----------------------------------------------------------------------------
// TTestOrb2IntfServerBase: Public, non-virtual methods
// ----------------------------------------------------------------------------
tCIDLib::TVoid TTestOrb2IntfServerBase::Dispatch(const TString& strMethodName, TOrbCmd& orbcToDispatch)
{
    if (strMethodName == L"Ping")
    {
        Ping
        (
        );
        orbcToDispatch.strmOut().Reset();
    }
     else
    {
         TParent::Dispatch(strMethodName, orbcToDispatch);
    }
}

