// ----------------------------------------------------------------------------
//  FILE: CIDWebSock_Shared.hpp
//  DATE: Mon, Dec 02 17:25:34 2019 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDWebSock
{
}

#pragma CIDLIB_POPPACK

