// ----------------------------------------------------------------------------
//  FILE: CIDWebSock_Shared.hpp
//  DATE: Fri, Nov 01 16:40:15 2019 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

// ----------------------------------------------------------------------------
// Types namespace
// ----------------------------------------------------------------------------
namespace tCIDWebSock
{
}

#pragma CIDLIB_POPPACK

