// ----------------------------------------------------------------------------
//  FILE: CIDWebSock_Shared.cpp
//  DATE: Sat, May 01 11:54:20 2021 -0400
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CIDWebSock_.hpp"

